### ISSUE TITLE
can't require 'version'

### ISSUE THREAD

**Issue by jcoyne** [mbklein/equivalent-xml#15]
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- equivalent-xml/version (LoadError)
	from /home/travis/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/travis/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/travis/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
	from /home/travis/.rvm/gems/ruby-2.0.0-p353/gems/equivalent-xml-0.4.1/lib/equivalent-xml.rb:1:in `<top (required)>'

**Comment by mbklein** [comment]
Haven't seen this in a while. Closing this issue to make sure that it comes back. 😄
