### ISSUE TITLE
Can we have a new version on rubygems.org? Please??

### ISSUE THREAD

**Issue by tingulfsen** [mbklein/equivalent-xml#31]
equivalent-xml is awesome, except the latest version on rubygems.org does not appear to contain this commit:

https://github.com/mbklein/equivalent-xml/commit/a843004664efd5c7bd922d1ef093650bfc3480ac

It would be great to get a new version up on rubygems.org so we could all use this feature without pulling straight from the GitHub repository.

Thanks!
tommy

**Comment by mbklein** [comment]
Great timing! I released one yesterday afternoon. Version 0.6.0 is up to date with the current master branch.
